CC=gcc
CFLAGS=-I.

servermake: server.o temps.o req.o getTrains.o cellule.o ../common/dialogue.o server2.o temps.o req.o getTrains.o cellule.o ../common/dialogue.o
	gcc -o server server.o temps.o req.o getTrains.o cellule.o ../common/dialogue.o -I.
	gcc -o server2 server2.o temps.o req.o getTrains.o cellule.o ../common/dialogue.o -I.